# Generated by Django 3.2.16 on 2023-05-21 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0005_auto_20230521_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='birthday',
            old_name='tag',
            new_name='tags',
        ),
    ]
